### ISSUE TITLE
SaviR function for pulling in hospital data?

### ISSUE THREAD

**Issue by mrajeev08** [CDCgov/SaviR#58]
@beansrowning do you want to drop in some details on what you were thinking this function should do? and I can try to tackle it over your vacation:)

**Comment by beansrowning** [comment]
Cool!

I would maybe start from here:

https://github.com/CDCgov/ITF_Power_BI/blob/master/Rfunctions/get_hospital_data.R

We want the return to be a time series, similar to get_vax() and others. 

Internal to most of the data functions, I've been using a lookup table to handle all the data connections, so any new ones might be added there:

https://github.com/CDCgov/SaviR/blob/master/R/lookups.R#L140

..and an example of how that gets called in:

https://github.com/CDCgov/SaviR/blob/master/R/get_covid_sources.R#L26

That also has the added benefit of being tested in the CI pipeline using this unitest that loops over the data source list:

https://github.com/CDCgov/SaviR/blob/master/tests/testthat/test-data_sources.R

**Comment by beansrowning** [comment]
Closed in #61
