### ISSUE TITLE
Update data source for HK, Macau, and Taiwan

### ISSUE THREAD

**Issue by beansrowning** [CDCgov/SaviR#83]
JHU+OWID have discontinued their time series data, so we'll need to pull these data from primary sources.
See: https://github.com/owid/covid-19-data/issues/2784, https://github.com/CSSEGISandData/COVID-19/issues/6577

**Comment by sondreus** [comment]
Just dropping in to say that if there is any way you can then feed these back to OWID (and have them incorporate it) that would be great.

**Comment by beansrowning** [comment]
@sondreus Always happy to contribute whatever we build out, though I guess that would be up to OWID to decide whether they'd like to incorporate.
